name: chadbot
description: Chadbot Application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  amazon_cognito_identity_dart_2: 
  async: ^2.11.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
 # data_connection_checker: 
  email_validator: ^3.0.0
  equatable: ^2.0.5
  firebase_core: 
  firebase_crashlytics:
  firebase_messaging: 
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^17.2.3
  flutter_phoenix: ^1.1.1
  flutter_styled_toast: ^2.2.1
  fixnum: ^1.1.0
  http: ^1.1.0
  image_picker: ^1.0.0
  kiwi: ^5.0.1
  protobuf: ^2.1.0
  progress_indicators: 
  path_provider: 
  rflutter_alert: ^2.0.4
  shared_preferences: ^2.3.3
  share: 
  screenshot: 
  sqflite: ^2.4.0
  device_info_plus: ^9.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand/fontquicksand.ttf
  assets:
    - assets/images/
    - assets/profile/

  uses-material-design: true

